import type, { Metadata } from "next";

import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";

import "./globals.css";
import Footer from "@/components/footer";

const font = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "dark")}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
